version: "3.9"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      - ETCD_NAME=etcd0
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ROOT_PASSWORD=rootpassword123 
    volumes:
      - etcd-data:/etcd-data
    ports:
      - "2379:2379"  # Client API
      - "2380:2380"  # Peer communication

volumes:
  etcd-data:
